### ISSUE TITLE
스타일 린트 패키지 버전을 production level 로 올리기

### ISSUE THREAD

**Issue by soomtong** [fastcampus/stylelint-config#9]
이 패키지는 F/E 개발 환경 구성에 필수로 쓰여지고 많은 도움을 받고 있습니다.
1.0 까지는 아니더라도 0.1.0 이라도 올려보면 어떨까 싶어요.

저는 1.0.0 찍고 함께 써도 좋을 듯 해요!

**Comment by jaewon-noh** [comment]
1.0.0버전 publish되었습니다.
이슈 닫도록 하겠습니다~
